### PR TITLE
feat/add-user-phone-field

### LINKED ISSUE #2: [BE] Add telephone in register user
- [x] Add telephone field in Register User
- [x] Add telephone field in Database
- [x] Update documentation

### PR DESCRIPTION
**Pull request by RodrigoRVSN**
Solves issue #2 

**What's being changed**

- New field optional `phone` in `User` database table
- Adjust in roles Enum

### CODE REVIEW

**Review by nata-vito — APPROVED** [review]
That's is so crazy man! Congrats for your work! Is nice have you in our team!!!

**Review by mayoral-leonardo — APPROVED** [review]
All safe.

**Comment by RodrigoRVSN** [comment]
@gianlucabueno makes more sense to keep required for all users roles direct, so i'll make this field required here

**Review by gianlucabueno — APPROVED** [review]

**Review by mayoral-leonardo — APPROVED** [review]
All safe.

**Pull request merged**
